name: action de saludar
description: test action de saludar
inputs:
  saludar-a:
    description: nombre a saludar
    required: true
    default: "Mundo."

runs:
  using: composite

  steps:
  - name: paso saludo
    run: echo "Hola ${{ inputs.saludar-a }}"
    shell: bash

  - name: fecha actual
    run: date
    shell: bash
