name: creando archivo saludo
on: [push]

jobs:
  saludo:
    runs-on: ubuntu-latest

    steps:
    - name: hola mundo
      run: echo "Hola Mundo"
    
    - name: create results directory
      run: mkdir results

    - name: touch file
      run: touch results/saludo.txt

    - name: set text
      run: echo "Hola Mundo" >> results/saludo.txt

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-file-upload
        path: results/saludo.txt
