name: "usando una variable de repositorio y secreta"

on: [workflow_dispatch]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    env:
      My_VAR: mi variable de entorno

    steps:
    - name: test variable de repo
      run: echo "el valor es ${{ vars.REPO_MI_VAR_1 }}"

    - name: variable secreta"
      run: echo "valor secreto ${{ secrets.MI_SECRET_VAR1 }}"