name: "ejemplo de usando una variable directamente"

on: [workflow_dispatch]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    env:
      My_VAR: mi variable de entorno

    steps:
    - name: test variable
      run: echo "el valor de $My_VAR"