name: test composite action
on: [workflow_dispatch]

jobs:
  my-local-action:
    runs-on: ubuntu-latest

    steps:
    - name: checkOUt code
      uses: actions/checkout@v3

    - name: usando saludar-a
      uses: ./.github/actions/saludar-nombre
      with:
        saludar-a: Tomi
